language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "ObqKj6DNejPazcqHkxpUFoF8aqiFyyMQdKW5OeXiKnKC6skdp3hmR/pWf9AeTZrhJ0dMfpdkauhZE0macagpQLZxU7D2Uf3uSLZfulY+aOz0ADNQbmb/kbHvGzZicXkhZKeB1ke4bQTmjfZuIOA3AC1nqBwuncCt8yUL8aW5FurmBJNTIsl+uwSveuvWGtMd/TDvLdDXn72yGIBbd21KlJIZpoA1YjcvKGASnXs+ERYQWfYmPl5L0qi+xSIio0slgLNWuj6CQCmmM4sf60LbKZELBD4TTZtIIy8ycYnR8JKWJYZ053VO79xXcltr0sgUhuw2WCTF9Xt7zfVK1xor1Y+ujlOFCNj/22/uoXf7nOh37WKRLIHuAFi3E8QPBi3s9e9iSyD9OkEaZKBBYROTPUtUmMIk1G/ronHPyPSaXA7d8QbDWMuQpfkPk5Qhhfwe7iWIhv/EcRRIuvS8lKnbXOmDzFWmvahi/ECpXGdPr+L9lX9LNPc5rP5WX8a3GVa35HZ4OkTH85ByDXWv3W5wRvShDBQo8t7+kfGZMW4D/b/by5INztEHCa6cHCzpEPGtAH9VnQJXfUlTynEKg8JssmktcN+ZpApqLQ3j71nnW78dVeWwpvGiiwx0jrDmLht3kFPFDSDi5t8CdmumF7NdHSy0OfcAC590bWtRASKndsk="
  project: "ceyb-website"