language: node_js
node_js:
  - "node"
warnings_are_errors: false
script:
  - yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "V7ds3nQAz+7JFipod/KBWdz/WWzedgdI8I8fKuJe9+uE3LU8UkPtiaTgSfDImkf+ckdZ0RwVAZeuDvVWN4F1bCyXl9tGpLHWI64CfxyY5q9LNKAfRDlL9+bIVlC/ZT1AZtJGZavxzPfQftdJb75W8OunGjwGdvzHogymvkogSdrMOXc4uC7GySphLepV/Eb1DGsaiKY50iEp5EW3DGQGy+oZvDF83LsB0AgRi4RAYR/hxks0zFVC18H0GWPdEzO4+iPLZ3cBoIqgapo3+34GtwcwShAolqh7VaI9CPmIyAUZOAHcz5ood+0uoBEpDmfzFKvoBa6dh0fQXnpOwlkWcapTgcH9NSuwFB9zcpObntUf/1/MVYl8ijKVc68XzMcNjDutLD3H1vlv2eX9uC34vvKlZ3bVuCuro+3QH70PMTI1gYv6q0aErpn4Iz9E89Yt4oTtSMeqhWaaQqmg3rNMtwhbozbawVflHKMsMuyCq8bvfV///r8Umv5yRlMMX5QOG+CImavWdNLVIpaObM4AbvU0D246nht/x+FqhXM4EE3o0pQNjQsKoDXEefiLozxLSf6GguvMdHoZ8n6j/M61V+WNU3f57YVdSP62Wtaxc3dt5wvpleOp06B7Ouls2osrNtKWrRbbmqWNZ5DqQ4bwSw2fgb11tAVITRe/6gBTbLE="
  project: "ceyb-website"
# env:
#   global:
#     secure: l47H9ZzqXpOdzrEkmb1Z8nCGDRyTlDYmYyl57GrwWgTRQ1tfAaeeoOtl/L8P8x+rTKOplN1PU62zOv5b0e+EYdZQ4Oi18euPXRnUHFeJ/lTXCn4l+APPdIMgJJsplyEDSfVTHpJ8K6orZV8ZgXN/EgJAY9vgAplB9VLT6XFvFG7vJReCDiLyucS+xWDzhBVH+haNI1kk/0MhokYYLB3V5rAc/R3cAkOC4bBKs+6DHUrmor+JGnIAl8IMxakMIMypharrfMzkMDhIqX/2nAqo+s4rD5IRsR8s0xA3FADBzjwx6rQeaqCu57MxC5DDNiRybZT/paSzFWkxSdULuQI5NYuddbAyjNxgo3o6dgTbQi0g4toxuhq7nzyfkTuB4cZvZS+NoXQouSQsbePZMDQ9kTFn2i0cHOzcljZObSNhzhoh0ta5U6UhnfQXMiVCINGsIDQnVDNAbNDw3amwkiba3JDxPY6wbhM8Dg78lxKolGf6DIfSGGBpP5zdS+0/T0KKvQ9eB87LJcXLvNWrN2u3s4xwabyHq9mKvb1yMzFUVdNkSdsOGO+PljQqVZt+Jr/YgDAu9wYWMaxG6j7GDiTxWwEesnn36ZsmLJiLhZqHduAwO8QnEdRMJSPGOOgiQXo2pzD0tzMWfxno1pyJPBPcw2N9nZ5hYBcVowCv4DsGtoU=
