language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "PnvyVrMwAw9ZjK7m6pln3sZ9BZsrwXnRlYTEOlLplVmU/31VSzw9hnO/VReARjf6lzenJBw40Q0aHRXDeot0MIQ6GzrfTAt8AEjuCRQu0NwTqTt5zz5XhfZFNUAyufI3TxQV9dbH+CYyNrgLLZVOXcTyHSecm1Au96UipgPb/fCIMta4nJ1bWlv6gKEDEfrhtCHrn/FseVyjyHFNAaUGl13sVGsmtt5BrkM3eDD3kA7bX7p3qkZU7/hrBIwecqZXOBlya5P6U7Cx/n+UPC+LJ+EYjRZGTvHTFOSvwVdPhrTz9ulF0VBZLRMgoPreihwhFZfQQZVIAlI2plCmZVF2ReyhwlybExwMIvIf/HqL+MBla2IHGka4OvSTygaPNM5StCXSj9aBvGX+KoAPTGohrMH+ZMx22MATnOg9YvWIGWWxv1Y5ZmBz2tOET106xeeFtPA6jBjo+m7HNJnFM1efX8k72fScJPT3EFWIc8TuFYVNYpwarUVpClTc9nsZj0F00h1tRQCFZQQ777LT+JzR0gMeMXS8zr6kpp+PbgMU8xz4pUEKA7WFgq9SbGwcHfJpoPVl2lZyG1oTIz1K/g8zDuErJCeUE/KwrDEyjGw1OvI3epDJj57PtvkyDvLyTxfmDYzERgmkX4m1VRQ7YdrweAGfo558WzwJYgRLxzXrc10="
  project: "ceyb-website"