language: node_js
node_js:
  - "node"
warnings_are_errors: false
script:
  - yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: Dbbw5Xtj73CbSoCEA8TthnXMED7IENrAC0MhJQh6iMpReh0mYT9S+dQSP+HoDw1vj+ACig0h5MGB8DMyxvzfUVjvZrRiRIMyyaNzCEX812feiMmxpo7zDXhSnhhiUWpihMw0vFursGaEHhsMe6eC5Oz+1PVfZF3fAfxL71yoWN7+ae5tvKchnxccEBLq9LE++8irTGzYNkEJ3RUHDLixDxnhm5L2tJrch3Qgh1VXTz98Uiojv5v8WFFXMh3Pu0h54SewvG5r79p14bdkLKLWIZTSsZrhIXnbI//A1tFcoPeKNMNHOE6aCyVrhApbPyLjQWy+LNV+o5AGSVx9aB36J0vPCLEg4bh3R8nOrhboczj1akoJR/pCdL4/+E0pViFBk9dBVytMv30xNtzKE13w6Ks7b7zjtews3NOFbqR85BsEqHH+LsCo0gvrYhbJ8SLHOJ8jIILomIhQQZwTH4k26Ry2+Ep0BiLQb/5ateUjayafNZzOlTZ578NFkExiA+YV8iK8EzIK8fUhoEjsBYO0KW8ke4QVD6eZLq4Rn9kcOO7vUPXdZPTbdHixrzCBfnS+FhnDx/6p8EfCRP9WbvlyMvKyi6j0Fu6SMlRoc4v48IDHJ2+AIH/l8YiCJUJmgf5q8wK6gTP5si5VPW/upqLCthhiziikm3wSFt6jXI8+1JE=
  project: "ceyb-website"
# env:
#   global:
#     secure: l47H9ZzqXpOdzrEkmb1Z8nCGDRyTlDYmYyl57GrwWgTRQ1tfAaeeoOtl/L8P8x+rTKOplN1PU62zOv5b0e+EYdZQ4Oi18euPXRnUHFeJ/lTXCn4l+APPdIMgJJsplyEDSfVTHpJ8K6orZV8ZgXN/EgJAY9vgAplB9VLT6XFvFG7vJReCDiLyucS+xWDzhBVH+haNI1kk/0MhokYYLB3V5rAc/R3cAkOC4bBKs+6DHUrmor+JGnIAl8IMxakMIMypharrfMzkMDhIqX/2nAqo+s4rD5IRsR8s0xA3FADBzjwx6rQeaqCu57MxC5DDNiRybZT/paSzFWkxSdULuQI5NYuddbAyjNxgo3o6dgTbQi0g4toxuhq7nzyfkTuB4cZvZS+NoXQouSQsbePZMDQ9kTFn2i0cHOzcljZObSNhzhoh0ta5U6UhnfQXMiVCINGsIDQnVDNAbNDw3amwkiba3JDxPY6wbhM8Dg78lxKolGf6DIfSGGBpP5zdS+0/T0KKvQ9eB87LJcXLvNWrN2u3s4xwabyHq9mKvb1yMzFUVdNkSdsOGO+PljQqVZt+Jr/YgDAu9wYWMaxG6j7GDiTxWwEesnn36ZsmLJiLhZqHduAwO8QnEdRMJSPGOOgiQXo2pzD0tzMWfxno1pyJPBPcw2N9nZ5hYBcVowCv4DsGtoU=
